### ISSUE TITLE
Support for Stage Blocks?

### ISSUE THREAD

**Issue by fvumbaca** [azohra/strapped#16]
It would be awesome if strapped can support the use of blocks to categorize different "stages" of a strapped file.

Something like:
```yaml
strapped:
  stage: scripting
  repo: repo.strapped.sh

brew:
  packages:
    - { name: python, upgrade: true }
    - { name: ruby, upgrade: true }
---
strapped:
  stage: emacs
  repo: repo.strapped.sh

brew:
  packages:
    - { name: emacs, upgrade: true }
  casks:
    - { name: emacs, upgrade: true }

bash:
  ln:
    - { target: ~/strapped/config/init.el, name: ~/.emacs.d/init.el, symbolic: true }
    - { target: ~/strapped/config/config.org, name: ~/.emacs.d/config.org, symbolic: true}
```

This can open up some cool use cases where users can run a subset of stages, or import stages from another yaml file:

```sh
$ strapped -y https://github.com/some/raw/yaml.yaml --stages emacs
```

or from a yaml:

```yaml
strapped:
  stage_src: https://github.com/some/raw/yaml.yaml
  stage: referenced_stage
---
strapped:
  stage: custom
  repo: repo.strapped.sh

# ....
```
