### ISSUE TITLE
Solidify version system

### ISSUE THREAD

**Issue by MatthewNielsen27** [azohra/strapped#8]
**Is your feature request related to a problem? Please describe.**
We need a good way to generate new versions of straps, and chose which version we want to use on a per-strap level

**Describe the solution you'd like**
Specify which version of a strap we would like to use with respect to a repo

**Describe alternatives you've considered**
Always use latest version 👎

**Comment by MatthewNielsen27** [comment]
# Updates

## Compiler

Users now must specify a `version` in their strap's `spec.yml` file. The compiler will first generate the  strap and then update the contents of the `/latest` directory for each strap.

```yml
strap:
  namespace: npm
  # User must specify a version
  version: v0.1.0
  description: "installs node.js packages globally"
  compatability: universal
  deps:
    - npm
  routines:
    packages:
      exec: "npm install -g ${name}"
      message: "installing ${name}"
      emoji: ☕
      input:
        - { name: testcafe }
```

If the user does not specify a proper version for the strap, they will receive this error message and their compilation will fail.

```console
[Build] creating strap for npm
[Build] Error: Invalid version field for strap npm.
[Build] Fix: add a version number to your strap, 'latest' does not count as a version number.
make: *** [straps] Error 1
```


## Runtime

Users can specify the version of each strap they want on a per-strap level. If the `version` field is left blank, the the latest version of the strap will be used.

```yml
# Version v0.1.0 of the bash strap will be used
bash:
  version: v0.1.0
  echo: 
    - { msg: "hello world" }

# The latest version of the npm strap will be used
npm:
  package:
    - { name: typescript } 
```
